---
- name: conveying files via template
  template:
    src: "{{item.src_file}}"
    dest: "{{item.dest_file}}"
  loop:
    - {
        src_file: "nginx.conf.j2",
        dest_file: "/etc/nginx/nginx.conf",
      }
    - {
        src_file: "minimum.rb.j2",
        dest_file: "/home/ruby/blog/config/unicorn.rb",
      }  
    - {
        src_file: "blog.service.j2",
        dest_file: "/etc/systemd/system/blog.service",
      }  
    - {
        src_file: "database.yml.j2",
        dest_file: "/home/ruby/blog/config/database.yml",
      }   
  notify:
    - reload_nginx
    - reload_postgresql
    - blog_service

- name: remove simlink default
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify:
    - reload_nginx   
